name = "transparent-mac"
account_id = "2ccb840de076261467812cbc32f8aa47"
workers_dev = false
compatibility_date = "2021-11-08"
main = "workers-site/index.ts"

[durable_objects]
bindings = [
    {name = "ETHERNET_ZONE", class_name = "EthernetZone"}
]

[[migrations]]
tag = "v1"
new_classes = ["EthernetZone"]

[site]
bucket = "./build"
exclude = ["BasiliskII.wasm.map"]

[env.production]
routes = [
    {pattern = "system7.app/*", zone_name = "system7.app"},
    {pattern = "macos8.app/*", zone_name = "macos8.app"},
    {pattern = "kanjitalk7.app/*", zone_name = "kanjitalk7.app"},
    {pattern = "mac.persistent.info/*", zone_name = "persistent.info"},
]
durable_objects.bindings = [
    {name = "ETHERNET_ZONE", class_name = "EthernetZone"}
]
